// Code generated by MockGen. DO NOT EDIT.
// Source: dependencies.go

// Package mock_watcher is a generated GoMock package.
package mock_watcher

import (
	context "context"
	reflect "reflect"

	replica "github.com/floppyzedolfin/sync/replica/replica"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// Mockserver is a mock of server interface.
type Mockserver struct {
	ctrl     *gomock.Controller
	recorder *MockserverMockRecorder
}

// MockserverMockRecorder is the mock recorder for Mockserver.
type MockserverMockRecorder struct {
	mock *Mockserver
}

// NewMockserver creates a new mock instance.
func NewMockserver(ctrl *gomock.Controller) *Mockserver {
	mock := &Mockserver{ctrl: ctrl}
	mock.recorder = &MockserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockserver) EXPECT() *MockserverMockRecorder {
	return m.recorder
}

// CreateDir mocks base method.
func (m *Mockserver) CreateDir(ctx context.Context, in *replica.CreateDirRequest, opts ...grpc.CallOption) (*replica.CreateDirResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDir", varargs...)
	ret0, _ := ret[0].(*replica.CreateDirResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDir indicates an expected call of CreateDir.
func (mr *MockserverMockRecorder) CreateDir(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDir", reflect.TypeOf((*Mockserver)(nil).CreateDir), varargs...)
}

// Delete mocks base method.
func (m *Mockserver) Delete(ctx context.Context, in *replica.DeleteRequest, opts ...grpc.CallOption) (*replica.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*replica.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockserverMockRecorder) Delete(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockserver)(nil).Delete), varargs...)
}

// PatchFile mocks base method.
func (m *Mockserver) PatchFile(ctx context.Context, in *replica.PatchFileRequest, opts ...grpc.CallOption) (*replica.PatchFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PatchFile", varargs...)
	ret0, _ := ret[0].(*replica.PatchFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchFile indicates an expected call of PatchFile.
func (mr *MockserverMockRecorder) PatchFile(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchFile", reflect.TypeOf((*Mockserver)(nil).PatchFile), varargs...)
}
